[package]
name = "bevy_extended_ui"
version = "1.0.0-beta.1"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]
description = "Create simply ui's with css and html for bevy."
license = "Apache-2.0"
repository = "https://github.com/exepta/bevy_extended_ui"
readme = "README.md"
keywords = ["bevy", "ui", "slider", "css", "html"]
categories = ["gui", "rendering"]

[lib]
name = "bevy_extended_ui"
path = "src/lib.rs"

# Bevy 0.17.0 main library
[dependencies.bevy]
version = "0.17.2"
default-features = true

# Html Converter
[dependencies.kuchiki]
version = "0.8.1"

# Css3 Converter
[dependencies.lightningcss]
version = "1.0.0-alpha.68"

[dependencies.once_cell]
version = "1.21.3"

[dependencies.regex]
version = "1.12.2"

[dependencies.bevy-inspector-egui]
version = "0.34.0"

[dependencies.notify]
version = "8.2.0"
