[package]
name = "bevy_extended_ui"
version = "0.2.1"
edition = "2024"
authors = ["Daniel Ramke <genshin.exepta@outlook.com>"]
description = "Create simply ui's in bevy like react from javascript"
license = "Apache-2.0"
repository = "https://github.com/exepta/bevy_extended_ui"
readme = "README.md"
keywords = ["bevy", "ui", "slider", "css", "html"]
categories = ["gui", "rendering"]

[lib]
name = "bevy_extended_ui"
path = "src/lib.rs"

# Bevy 0.16.0 main library
[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_text",
    "bevy_ui",
    "default_font",
    "multi_threaded",
    "png",
    "jpeg",
    "gif",
    "ico",
    "webp",
    "bevy_mesh_picking_backend",
    "bevy_picking",
    "custom_cursor",
    "bevy_ui_picking_backend",
    "bevy_winit",
    "x11",
    "bevy_log"
]

# Html Converter
[dependencies.kuchiki]
version = "0.8.1"

# Css3 Converter
[dependencies.lightningcss]
version = "1.0.0-alpha.67"

[dependencies.once_cell]
version = "1.21.3"

[dependencies]
regex = "1.11.1"

[dependencies.bevy-inspector-egui]
version = "0.31.0"